name: deploy

on:
  workflow_run:
    workflows: [ build ]
    branches: [ release/10 ]
    types: [ completed ]

jobs:
  deploy:
    name: Deploy release/10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Deploy Docs
      run: mvn -B deploy -P publish-release-10
